name: "PHP CodeSniffer Validations"
on: [push, pull_request]
jobs:
  validate-code-style:
    name: PSR-12 Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Validate composer.json and composer.lock
        run: composer validate 

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
          
      - name: Cache composer dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer

      - run: package-installer packages.txt
        if: steps.cache-packages.outputs.cache-hit != 'true'

      - name: Install PHP CodeSniffer Composer package
        run: composer global require "squizlabs/php_codesniffer=*"

      - name: Validate PSR-12 code Style
        run: ~/.composer/vendor/bin/phpcs