- name: Setup PHP Action
  uses: shivammathur/setup-php@2.11.0
  with: 
    php-version: '8.0'
    tools: phpstan, composer

- name: Validate composer.json and composer.lock
  run: composer validate

- name: Get composer cache directory
  id: composercache
  run: echo "::set-output name=dir::$(composer config cache-files-dir)"